### ISSUE TITLE
Conversion errors on MPRAGE datasets

### ISSUE THREAD

**Issue by julienbesle** [xiangruili/dicm2nii#4] opened 2018-06-03 14:02 UTC
The two following MPRAGE datasets are not converted correctly:
testJulien_COR-T1W_3D_TFE SENSE_7_2.PAR
testJulien_TRA-T1W_3D_TFE SENSE_7_3.PAR
located in the dropbox folder I shared previously:
https://www.dropbox.com/sh/p0wp7t4j39xiyj8/AAAJEDJghg8wFKWPRLFzvYgBa?dl=0

The first results in the following error:
```
Validating 1 files ...
 No valid files found:

Index exceeds matrix dimensions.
.

```
The second is converted without error, but I cannot open it using fslview; I get this error:
`Missing header/ Image file`

**Comment by xiangruili** [comment] 2018-06-04 01:03
The first failure must be due to a bug introduced when SortFrames is implemented in last commit. I am improving that part of the code, and my current version won't replicate the error. So it should be fixed after next commit.

For file testJulien_TRA-T1W_3D_TFE SENSE_7_3.PAR, I am getting a different error which fails to read the value table in PAR. The cause is due the question marks for one of the columns where numeric is expected. Is this possible behavior from Philips, or is it introduced by other program, like xml2par?

**Closed** 2018-07-16 23:18 UTC
